[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Matthew Baxter <matthewbaxter0412@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
